# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69fbf999319a19dc3f7b59e75c95b34ccdd5920ecc2005941f740160d1ba6bca5af386aa12b605be181ef77ac97ece53f130c847e8ca6852ceded23ed6c2b78

test:
  secret_key_base: 96b107868291945036f23f251a961e4c0229c35ae6ff25ca8d1d5c800171a78d77d25827977d795e6d69585bcb301ea756dff9e4e91f1d3685b806277e207bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
